auto configure JAVA_HOME

diff --git a/vagrant/hadoop_build/ansible-hadoop/roles/common/templates/hadoop-config.sh.j2 b/vagrant/hadoop_build/ansible-hadoop/roles/common/templates/hadoop-config.sh.j2
--- a/vagrant/hadoop_build/ansible-hadoop/roles/common/templates/hadoop-config.sh.j2
+++ b/vagrant/hadoop_build/ansible-hadoop/roles/common/templates/hadoop-config.sh.j2
@@ -1,18 +1,19 @@
 set -e
 
-export JDK_DEVEL_PKG_VER=java-1.7.0-openjdk-devel-1.7.0.65-2.5.2.5.fc20
-#Ubuntu
-#export JAVA_HOME=/usr/lib/jvm/java-7-openjdk-amd64/jre/
-#export JAVA_HOME=/usr/lib/jvm/java-6-openjdk-amd64/jre/
-#Centos-7
-export JAVA_HOME=/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.65-3.b17.el7.x86_64/jre/
-#export JAVA_HOME=/usr/lib/jvm/jre-1.7.0-openjdk.x86_64/
-#export JAVA_HOME=/usr/lib/jvm/jre-1.7.0-openjdk/
+# Determine JAVA_HOME
+WHICH_JAVA=$(which java)
+if [ $? -ne 0 ]; then
+  echo "ERROR: Could not find java, is it installed?"
+  exit 1
+fi
+ALTERNATIVES_JAVA=$(readlink $WHICH_JAVA)
+export JAVA_HOME=$(readlink $ALTERNATIVES_JAVA | sed 's|bin/java||g')
+
+
+# Hadoop vars
 export HADOOP_INSTALL_DIR={{ hadoop_install_dir }}
 export HADOOP_ARCHIVE=/tmp/hadoop.tar.gz
 export MR_SCRIPT=test-pi-yarn.sh
-
-#hadoop home is here irrespective of version
 export HADOOP_HOME=${HADOOP_INSTALL_DIR}/hadoop
 export CORE_DEFAULT=${HADOOP_HOME}/etc/hadoop/core-default.xml
 export CORE_SITE=${HADOOP_HOME}/etc/hadoop/core-site.xml
